

name: Valint non-root demo

on: 
  push:
    branches:
      - 'pre-release**'
      - 'release**'
  workflow_dispatch:
  pull_request:
  #   branches:
  #     - 'pre-release*'

jobs:
  non-root:
    runs-on: ubuntu-latest
    steps:

      - name: Get Actions user id
        id: get_uid
        run: |
          actions_user_id=`id -u $USER`
          echo $actions_user_id
          echo "USERID=$actions_user_id" >> $GITHUB_ENV
      
      - run: |
          printenv
          echo "Using $USER ($USERID)"

      - name: Run non root valint
        id: valint_json
        uses: scribe-security/action-bom@v0.4.2
        with:
           target: 'busybox:latest'
           verbose: 2
           format: json
           force: true
           output-file: non-root.sbom.json
        env:
          USERID: ${{ env.USERID }} ## Usally '1001' for github hosted workers
          USERNAME: ${{ env.USER }} ## usally 'runner' for github hosted workers 

      - name: Show user info
        run: |
          id
          ls -lhR scribe
          rm -rf scribe/valint